name: Language Pie Chart

on:
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

jobs:
  lang-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Language Chart
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: lang-chart.svg
          user: iftekharanwar
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, bytes-size
          plugin_languages_indepth: yes
          config_display: large

      - name: Commit Chart
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update language chart"
          file_pattern: lang-chart.svg
