name: GitHub Skyline

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  skyline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Skyline STL
        uses: mhutchie/github-skyline@main
        with:
          user: iftekharanwar
          year: 2025

      - name: Commit Skyline
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github skyline"
          file_pattern: "*.stl"
